CPPFLAGS = -I/usr/X11R6/include
LDFLAGS = -L/usr/X11R6/lib -lglut -lGLU -lGL

PROGS = example-4-1 example-4-2 example-5-1 example-5-3 example-5-4-1 example-5-4-2 example-6-1 example-6-2 example-7-1-1 example-7-1-2 example-7-1-3 example-7-2 example-7-3 example-8-1

default: $(PROGS)

clean:
	rm -f $(PROGS) *.o a.out
